### ISSUE TITLE
404 File not Found

### ISSUE THREAD

**Issue by pipe89** [Seeed-Studio/pi_repo#1]
Do you want to continue? [Y/n] y
Err:1 https://seeed-studio.github.io/pi_repo stretch/main armhf librespeaker armhf 2.1.0-build181009
  404  Not Found
E: Failed to fetch https://seeed-studio.github.io/pi_repo/pool/main/libr/librespeaker/librespeaker_2.1.0-build181009_armhf.deb  404  Not Found

pi@raspberrypi:~ $ sudo apt install respeakerd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package respeakerd

**Comment by KillingJacky** [comment]
Hi @pipe89 sorry for the inconvenience, this issue has been fixed.
